### ISSUE TITLE
Installation steps

### ISSUE THREAD

**Issue by mandolyte** [chrislusf/glow#1]
There's no "go get" command to show how to install, but I guessed with:
```
go get -u github.com/chrislusf/glow
```
which returned no errors, but when I did a go run on the first sample in README.md, I get this:
```
$ go run glow1.go 
../src/github.com/chrislusf/glow/flow/dataset_sort.go:7:2: cannot find package "github.com/psilva261/timsort" in any of:
	/usr/local/go/src/github.com/psilva261/timsort (from $GOROOT)
	/home/cecil/Workspace/src/github.com/psilva261/timsort (from $GOPATH)
$ 
```
Looks like there may be dependencies? Could you update the README to provide install instructions?

**Comment by chrislusf** [comment]
Actually the installation instructions should just be:
```
go get github.com/chrislusf/glow
```

However, I can reproduce this issue. But I do not understand why I still need to do:
```
go get github.com/psilva261/timsort
```

"go get" should handle the dependencies.

**Comment by ctd1500** [comment]
I've noticed that sometimes "go get" can act oddly, so I don't tend to use "go get github.com/user/repo". 
Instead, simply place the import in your code, such as making a main.go containing the sample from the readme.  In the same directory as your new main.go, type:

    go get

Without any parameters, it will download all of your imports and dependencies in your code automatically.
This worked perfectly for me with the sample.

**Comment by chrislusf** [comment]
@ctd1500 Thanks for the tip!

I just figured it out one minute ahead of your post. :)
