### ISSUE TITLE
cluster auth support

### ISSUE THREAD

**Issue by netroby** [chrislusf/glow#13]
would you please add support auth while connect the remote cluster ip:port 
for example. may like this 
```
--auth-key=si4C823CD$72^B512
```

**Comment by chrislusf** [comment]
Good suggestion!

But with this, anyone can see the auth key by doing "ps -ae".

What is the use case?

**Comment by netroby** [comment]
Remote cluster. different location , for example:  I have node in New York, and Los Angeles, And Dallas. We can make some interesting things if we can built remote cluster. but if no crypto or authenticate, the communication not security.

**Comment by netroby** [comment]
the auth key can be pass as flag , or may be read from configure file later

**Comment by JensRantil** [comment]
Alternative approach: Support reading the auth key from an environment variable? Should probably be logged that it is using an auth key on start-up, too to make it clear that it was picked up.

**Comment by chrislusf** [comment]
we can just start simple to pass the auth key via flags.

**Comment by chrislusf** [comment]
Added 2-way SSL to secure the Glow cluster. Now Glow cluster can run securely on any server across internet.

Example:
# start master
glow master --cert.file=~/ssl/localhost.cer --key.file=~/ssl/localhost.key --ca.file=~/ssl/ca.cer

# start one agent
./glow agent --dir ~/tmp/1 --port 8931 --cert.file=~/ssl/localhost.cer --key.file=~/s/localhost.key --ca.file=~/ssl/ca.cer --host localhost

# start another agent
./glow agent --dir ~/tmp/2 --port 8932 --cert.file=~/ssl/localhost.cer --key.file=~/s/localhost.key --ca.file=~/ssl/ca.cer --host=localhost

# start any driver program
./t -glow -cert.file=~/ssl/localhost.cer -key.file=~/ssl/localhost.key -ca.file=~/ssl/ca.cer -glow.driver.host=localhost
