### ISSUE TITLE
windows10  word-count run error

### ISSUE THREAD

**Issue by oldtree2008** [chrislusf/glow#14]
I try examples cluster. but run error .

![image](https://cloud.githubusercontent.com/assets/5414588/12077841/a690729e-b232-11e5-9383-fcf8f117b663.png)

**Comment by chrislusf** [comment]
I am guessing something wrong with the dash in the file name.

**Comment by oldtree2008** [comment]
word-count.exe -glow -glow.leader="localhost:8930"   with extension .exe .   is OK
but in cluster mode  without result  in console. why?

**Comment by chrislusf** [comment]
I would like know a little more about the last problem, "in cluster mode without result in console". Is it some user error?
