### ISSUE TITLE
Windows: undefined: syscall.SIGINFO

### ISSUE THREAD

**Issue by jgranduel** [chrislusf/glow#15]
Hi, 

I've tried to install glow on a go1.5.2 windows-7/amd64. I get this error when getting flow

    > go get github.com/chrislusf/glow/flow
    # github.com/chrislusf/glow/flow
    D:\Go\Code\src\github.com\chrislusf\glow\flow\utils.go:51: undefined: syscall.SIGINFO
    D:\Go\Code\src\github.com\chrislusf\glow\flow\utils.go:59: undefined: syscall.SIGINFO

I haven't found anything special on syscall and Windows yet (https://github.com/golang/sys/blob/master/windows/syscall_windows.go ?) but I'm really ignorant about this topics.

Thanks

**Comment by chrislusf** [comment]
Thanks for reporting this! This was broken by last night's check in. Please check whether the fix resolve your problem.

**Comment by jgranduel** [comment]
Hi, 

thank you for your answer. Unfortunately, it still doesn't install properly.
As glow was installed (first step go get github.com/chrislusf/glow was successful), I tried installing only flow ( go get github.com/chrislusf/glow/flow ), but this produced the same result.

Then, I manually uninstalled glow and reinstalled it with success. But this time, the second steps yields
  > go get github.com/chrislusf/glow/flow
  # github.com/chrislusf/glow/flow
  C:\Go\Code\src\github.com\chrislusf\glow\flow\signal_handling.go:21: undefined: syscall.SIGINFO
  C:\Go\Code\src\github.com\chrislusf\glow\flow\signal_handling.go:29: undefined: syscall.SIGINFO
  C:\Go\Code\src\github.com\chrislusf\glow\flow\signal_handling_windows.go:11: OnInterrupt redeclared in this block
  C:\Go\Code\src\github.com\chrislusf\glow\flow\signal_handling_windows.go:26: OnInterrupt.func1 redeclared in this block
  			previous declaration at C:\Go\Code\src\github.com\chrislusf\glow\flow\signal_handling.go:26
  			previous declaration at C:\Go\Code\src\github.com\chrislusf\glow\flow\signal_handling.go:11
  C:\Go\Code\src\github.com\chrislusf\glow\flow\signal_handling_windows.go:29: undefined:   	syscall.SIGINFO

Hope this is useful.
