### ISSUE TITLE
Windows: undefined: syscall.SIGINFO (reopened)

### ISSUE THREAD

**Issue by jgranduel** [chrislusf/glow#17]
Hi,

I'm reopening this issue as glow/flow didn't install properly this time neither. A regression might be introduced.

As glow was installed (first step go get github.com/chrislusf/glow was successful), I tried installing only flow ( go get github.com/chrislusf/glow/flow ), but this produced the same result as before.

Then, I manually uninstalled glow and reinstalled it with success. But this time, the second step yields:

    > go get github.com/chrislusf/glow/flow
    # github.com/chrislusf/glow/flow
    C:\Go\src\github.com\chrislusf\glow\flow\signal_handling.go:21: undefined: syscall.SIGINFO
    C:\Go\src\github.com\chrislusf\glow\flow\signal_handling.go:29: undefined: syscall.SIGINFO
    C:\Go\src\github.com\chrislusf\glow\flow\signal_handling_windows.go:11: OnInterrupt redeclared in this block
    C:\Go\src\github.com\chrislusf\glow\flow\signal_handling_windows.go:26: OnInterrupt.func1 redeclared in this block
    previous declaration at C:\Go\src\github.com\chrislusf\glow\flow\signal_handling.go:26
    previous declaration at C:\Go\src\github.com\chrislusf\glow\flow\signal_handling.go:11
    C:\Go\src\github.com\chrislusf\glow\flow\signal_handling_windows.go:29: undefined: syscall.SIGINFO

Hope this is useful.

**Comment by chrislusf** [comment]
Does it help to run:

 go get -u github.com/chrislusf/glow/flow

**Comment by chrislusf** [comment]
I just added travis to test on windows/darwin/linux and the "go get" works fine on all of them (there are some test errors due to test setup). So I am almost 99% sure it is due to old local version.

**Comment by jgranduel** [comment]
Thanks for your answer, 

Still not there and same output. I'll try on another Windows instance...
  > go get -u github.com/chrislusf/glow/flow
  # github.com/chrislusf/glow/flow
  C:\Go\src\github.com\chrislusf\glow\flow\signal_handling.go:21: undefineC: syscall.SIGINFO
  C:\Go\src\github.com\chrislusf\glow\flow\signal_handling.go:29: undefineC: syscall.SIGINFO
  C:\Go\src\github.com\chrislusf\glow\flow\signal_handling_windows.go:11: OnInterrupt redeclared in this block
          previous declaration at C:\Go\src\github.com\chrislusf\glow\flow\signal_handling.go:11
  C:\Go\src\github.com\chrislusf\glow\flow\signal_handling_windows.go:26: OnInterrupt.func1 redeclared in this block
        previous declaration at C:\Go\src\github.com\chrislusf\glow\flow\signal_handling.go:26
  C:\Go\src\github.com\chrislusf\glow\flow\signal_handling_windows.go:29: undefineC: syscall.SIGINFO

**Comment by chrislusf** [comment]
What's the go version?

**Comment by jgranduel** [comment]
go-1.5.2

    > go version
    go version go1.5.2 windows/amd64

**Comment by chrislusf** [comment]
Just got hold of a window system and fixed this.

**Comment by jgranduel** [comment]
Thank you very much, it worked this time with the -u option
   
    go get -u github.com/chrislusf/glow/flow

How come it did compile before?
