### ISSUE TITLE
Manage Dependencies

### ISSUE THREAD

**Issue by alpe** [chrislusf/glow#18]
`go get ./...` won't give you reproducible builds. A section in the Readme would be helpful.

**Comment by chrislusf** [comment]
could you please send a pull request for this. I am currently not 100% clear.

**Comment by alpe** [comment]
With `go get ./...` you'll always get the latest master. For reproducible builds you want to pin specific versions of your 3rd party libs. People usually use `vendoring` or dependency management tools. This page contains many options: https://github.com/golang/go/wiki/PackageManagementTools

**Comment by joeblew99** [comment]
Mhh dependency tooling. 
From what i can see Glow has none right now.
Well which one ? Thats always the question.
I use godep:
https://github.com/tools/godep/graphs/contributors

**Comment by chrislusf** [comment]
Golang's official "vendor" folder seems the right way to go though.

**Comment by joeblew99** [comment]
yes, but what to use with it is what i am raising

**Comment by JensRantil** [comment]
@chrislusf I think `glide` essentially relies on the official vendoring, it's simply a helper tool for that.

**Comment by chrislusf** [comment]
already using glide.
