### ISSUE TITLE
http server address and port should be configurable

### ISSUE THREAD

**Issue by alpe** [chrislusf/glow#23]
In https://github.com/chrislusf/glow/blob/master/driver/rsync/http_server.go#L91 is a random port selected which makes it very hard when access is restricted via firewalls or in a container environment where ports are exposed.
The remote address which is used with the heartbeat can be a local one. Then it's impossible for any client outside to connect. I had these problems when I tried to connect to a local docker cluster from the host system.

**Comment by chrislusf** [comment]
this was actually on my to do list. Do you want to pick it up? Just make the port number default to 0. Just let me know if it involves too much changes.

**Comment by alpe** [comment]
@chrislusf This isn't a blocker for me at the moment. I just wanted to make a note to not forget about it.

**Comment by chrislusf** [comment]
fixed now.
