### ISSUE TITLE
undefined: signal.Ignore

### ISSUE THREAD

**Issue by wenkesj** [chrislusf/glow#37]
# Signal Handling Linux #
I am recieving an error that seems to be OS specific. I haven't done very much reading, but I hope you can help.

### Error ###
Error I get when I `get/install` the packages.
![screen shot 2016-03-15 at 6 49 22 pm](https://cloud.githubusercontent.com/assets/7623062/13796739/c66a451a-eade-11e5-82e3-535c9944a54a.png)

### Operating system information ###
![screen shot 2016-03-15 at 6 51 07 pm](https://cloud.githubusercontent.com/assets/7623062/13796760/ea572592-eade-11e5-99c8-326512fe0a6d.png)

Thank you for the work that you are doing. This is going to be very helpful to my clustering project!

S

**Comment by chrislusf** [comment]
Need to upgrade the go version.

**Comment by chrislusf** [comment]
Closing this. Please let me know how it works for you, which will be very encouraging for me. Thanks!
