### ISSUE TITLE
any ideas to add Lua(LuaJIT)?

### ISSUE THREAD

**Issue by plandem** [chrislusf/glow#63]
it's quite fast (already using at high load systems). 

It would nice to have:
1) define flow dynamically
2) use lua code as map/reduce/filter and etc.

**Comment by chrislusf** [comment]
Not familiar with Go + Luajit together. I want to see an example that go streams []bytes to luajit code and get output as []byte, probably via an external luajit process.

**Comment by plandem** [comment]
well...right now i'm not ready to answer your question, but maybe this projects helps: https://github.com/mozilla-services/heka

p.s.: what would be nice - to have ability to make custom DSL or just make some strict rules for built-in scripting language to defines flows without recompilation. e.g.: we need daemon that spawn calculations with flows. flows will be changing time from time and recompilation is not possible in our case. So we are just looking for solution. Your library is looking very powerful and yet easy to learn.

**Comment by alaska** [comment]
Probably worth mentioning at this point that (unless I missed it on the dependency graph) LuaJIT would be the first cgo dependency glow has, thus complicating the build process and bringing all of the other fun nonsense that cgo comes with. If he's looking to keep the library pure-go, this isn't going to happen. There are pure-go Lua VMs, but none of them are on par with the C interpreters.

**Comment by chrislusf** [comment]
If going with LuaJIT, this would be a separate github project.

**Comment by plandem** [comment]
there is also another library about "flow", but mainly about flow programming: https://github.com/trustmaster/goflow

Well, so maybe i miss something, but is it possible to:
dynamically "recreate" flow without recompilation? E.g.: we have UI to build flow for processing incoming data. As output we have something DSL, json or whatever. After submit, "daemon" reload logic and recreate flow as designed. We can't have compiler to recompile each time. So any ideas?

**Comment by plandem** [comment]
@alaska the problem with pure Lua VM is in speed, i suppose. LuaJit is very fast. If we omit speed, then any other language can be taken, e.g. javascript. I started topic about LuaJit because it's already using at projects where speed is critical: 

tarantool, nginx, snabb switch, luvit.io, terralang and etc.

So it's already battle tested in highload. But if we are talking about our case - we need good speed, but also we need dynamic behaviour - ability to reload flow after some actions at UI side. I like Glow for learning curve - very easy to set/use, but right now can't decide how it can help us :(

**Comment by chrislusf** [comment]
working on https://github.com/chrislusf/gleam

It's a Glow + Luajit combination. Currently only single computer only. Please try it out first.

**Comment by plandem** [comment]
Wow, will try it soon. Looks like totally separate project. Looking forward for benchmarks :) it would be nice to see cons/pros of each library :)

**Comment by tejasmanohar** [comment]
@chrislusf is gleam the future of this project, or are they both active in separate lines?

**Comment by chrislusf** [comment]
@tejasmanohar Glow is left as is. It is working fine by itself. But the performance is about 10x or 20x slower.

**Comment by tejasmanohar** [comment]
@chrislusf sorry for issue hijacking :) - but more what i meant is... is there any reason you'd use glow over gleam once gleam becomes more mature / finishes up features on roadmap?

**Comment by chrislusf** [comment]
Glow has nice syntax and is more suited to some pure Go advocates' taste. That's it.

**Comment by tejasmanohar** [comment]
Gotcha, cool! Do Glow/Gleam optimize for in-memory computations or ...? Do you have any benchmarks on how this compares to something like Spark?

**Comment by chrislusf** [comment]
No Spark comparison. Its setup is too much.

Gleam supports both on disk and in memory operations.
