### ISSUE TITLE
Consider reduce the number of Travis CI builds

### ISSUE THREAD

**Issue by justicezyx** [chrislusf/glow#65]
Right now, the Travis CI builds for 12 environments, based a combination of OS and Go versions. The config shows:

os:
  - linux
  - osx
  - windows
  - freebsd

go: 
 - 1.5
 - 1.6
 - tip

Maybe we can reduce the build combinations to only for Linux, and only build on the previous major go version + tip; that reduces the builds from 12 to 2.

The benefit is that the build time will be reduce dramatically. The down side is that we lose the testing coverage on some OSes. IMHO, this trade-off favors reduced test time; mainly because the extra OSes does not seem have much presence for Glow's intended use cases, i.e., parallel batch processing.

WDYT?

**Comment by chrislusf** [comment]
I think the builds are executed in parallel?

**Comment by chrislusf** [comment]
I think we can skip freebsd, and only use the latest tip and latest official golang release.

**Comment by justicezyx** [comment]
Removing freebsd and 2 go versions SGTM, will make a change.

The builds appear to be run in parallel, but in reality there is queuing time, i.e., not all builds start simultaneously together. The build usually takes ~ 30 minutes.

> only use the latest tip and latest official golang release
According to Travis document [1]
```
You can use any tagged version of Go or use tip to get the latest version.
```
`tip` actually points the latest go release. I think you are referring to the previous and latest releases.

[1] https://docs.travis-ci.com/user/languages/go
