### ISSUE TITLE
any plan for hive like execution engine?

### ISSUE THREAD

**Issue by xtaci** [chrislusf/glow#78]
is there any plan for hive like execution engine? containing features like:
1. heterogeneous datasource joining and querying.
2. Parses and runs SQL query in mapreduce in glow.

**Comment by chrislusf** [comment]
https://github.com/chrislusf/gleam will have these features.

It already has support for csv and cassandra as starting examples.

**Comment by xtaci** [comment]
lots of database connectors are available in golang, so if it's possible, StorgeHandler specification could be addressed first, I think. Once the execution pipeline is sophisticated enough, contributors can provides db-drivers.
