### ISSUE TITLE
Issues at start_local_glow_cluster.sh

### ISSUE THREAD

**Issue by Alessar** [chrislusf/glow#82]
`etc/start_local_glow_cluster.sh`

`glow master --address="${MASTER_ADDRESS}" &>/dev/null &`  
each lines should be like  
`./glow master --address="${MASTER_ADDRESS}"`  
1. It allows to run glow application
2. It show errors at startup or logs

**Comment by chrislusf** [comment]
how about sending a pull request?

**Comment by Alessar** [comment]
#83
