### ISSUE TITLE
glow使用与部署方法怎么处理？

### ISSUE THREAD

**Issue by ardyli** [chrislusf/glow#88]

**Comment by ardyli** [comment]
> No description provided.

**Comment by idealeak** [comment]
加qq群吧，方便沟通------------------ 原始邮件 ------------------
发件人: "ardyli"<notifications@github.com>
发送时间: 2019年9月21日(星期六) 晚上6:41
收件人: "chrislusf/glow"<glow@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [chrislusf/glow] glow使用与部署方法怎么处理？ (#88)



lu 您好，目前在网上未找到您这个框架的详细的使用与部署方法。目前我想用于分布式计算，能否提供一个对该产品的一个系统介绍和部署说明内容？
 
&mdash;

**Comment by ardyli** [comment]
好的。QQ群号是哪个？



ardyli@126.com
 
发件人： idealeak
发送时间： 2019-09-21 19:04
收件人： chrislusf/glow
抄送： ardyli; State change
主题： Re: [chrislusf/glow] glow使用与部署方法怎么处理？ (#88)
加qq群吧，方便沟通------------------ 原始邮件 ------------------ 
发件人: "ardyli"<notifications@github.com> 
发送时间: 2019年9月21日(星期六) 晚上6:41 
收件人: "chrislusf/glow"<glow@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [chrislusf/glow] glow使用与部署方法怎么处理？ (#88) 



lu 您好，目前在网上未找到您这个框架的详细的使用与部署方法。目前我想用于分布式计算，能否提供一个对该产品的一个系统介绍和部署说明内容？ 

&mdash;
