### ISSUE TITLE
idea: grep in go

### ISSUE THREAD

**Issue by joeblew99** [chrislusf/glow#9]
https://sift-tool.org/index

this is a replacement for grep, and seems like it could be a nice match for glow in some ways.
its high perf and nicely extensible.

i kind of see it as a useful tool when you need to have glow orchestrate everything, and you need to sift through lots of files

curious what you think.

**Comment by chrislusf** [comment]
It has a nice web page and shocking performance numbers, but no explanation of the search algorithm.
